<a href="https://colab.research.google.com/github/Dicere/Machine_Learning_algorithms_from_scratch/blob/main/KNN_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Реализация всех алгоритмов/data_banknote_authentication.txt', header=None)
df.columns = ['variance', 'skewness', 'curtosis', 'entropy', 'target']
X, y = df.iloc[:,:4], df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [62]:
class MyKNNClf():
    def __init__(self, k=3,metric='euclidean'):
        self.k = k
        self.X = 0
        self.y = 0
        self.train_size = 0
        self.metric = metric
    def __str__(self):
        attributes = ', '.join(f"{key}={value}" for key, value in vars(self).items())
        return f"MyKNNClf class: {attributes}"
    def __repr__(self):
        attributes = ', '.join(f"{key}={value}" for key, value in vars(self).items())
        return f"MyKNNClf class: {attributes}"

    def fit(self, X_fit: pd.DataFrame, y_fit: pd.Series):
      self.X = X_fit.copy()
      self.y = y_fit.copy()
      self.train_size = (self.X.shape[0],self.X.shape[1])

    def metrics(self,X_test: pd.DataFrame):
      if self.metric == 'euclidean':
        res = np.sqrt(np.sum((self.X.values - X_test.values)**2,axis=1))
        return pd.Series(res,index=self.X.index)
      if self.metric == 'chebyshev':
        diffs = np.abs(self.X.values - X_test.values)
        max_diffs = np.max(diffs, axis=1)
        return pd.Series(max_diffs,index=self.X.index)
      if self.metric == 'manhattan':
        diffs = np.abs(self.X.values - X_test.values)
        manhat = np.sum(diffs,axis=1)
        return pd.Series(manhat,index=self.X.index)
      if self.metric == 'cosine':
        top = np.sum(self.X.values* X_test.values,axis=1)
        ground = np.sqrt(np.sum(self.X.values**2,axis=1))*np.sqrt(np.sum(X_test.values**2, axis=0))
        res = 1 - (top/ground)
        return pd.Series(res,index=self.X.index)

    def evristic(self, X_test: pd.DataFrame,chanse):
      index= self.metrics(X_test).sort_values()[:self.k].index
      if chanse ==0:
        if np.count_nonzero(self.y.loc[index] == 1) == np.count_nonzero(self.y.loc[index] == 0):
          return(1)
        return(self.y.loc[index].mode().values[0])
      if chanse ==1:
        one_count = np.count_nonzero(self.y.loc[index] == 1)
        return(one_count/self.k)

    def predict(self, X_test: pd.DataFrame):
        y_pred_vec = X_test.apply(lambda x: self.evristic(x,0),axis=1)
        return y_pred_vec

    def predict_proba(self, X_test: pd.DataFrame):
        y_pred_vec = X_test.apply(lambda x: self.evristic(x,1),axis=1)
        return y_pred_vec

In [63]:
X_test.columns[1]

'skewness'

In [64]:
instance = MyKNNClf(k=2,metric = 'cosine')

In [65]:
instance.fit(X_train,y_train)

In [66]:
y_pred_vec = instance.predict_proba(X_test)

In [67]:
y_pred_vec.value_counts()

0.0    257
1.0    195
0.5      1
dtype: int64

In [ ]:
list_values =[]
sum = np.zeros(X_train.shape[0])
for b in range(len(X_train.columns)):
  list_values.append(np.absolute(X_train.loc[:,X_train.columns[b]] - X_test.iloc[1,b]))

In [41]:
1 - np.sum(X_train.values* X_test.iloc[1].values,axis=1)/(np.sqrt(np.sum(X_train.values**2,axis=1))*np.sqrt(np.sum(X_test.iloc[1].values**2)))

array([1.08360878e+00, 3.74717564e-01, 4.72430205e-01, 1.03262567e-01,
       1.07306007e+00, 6.57751542e-02, 1.88617050e+00, 1.12746183e-01,
       7.20309641e-01, 1.83867102e+00, 4.49214816e-02, 1.81062984e+00,
       1.62239207e-01, 1.82527934e+00, 2.64596144e-01, 1.24662944e-01,
       1.22096053e+00, 1.84692686e+00, 1.79725176e+00, 1.89484854e+00,
       1.21251833e+00, 1.84974936e+00, 1.87921102e+00, 1.83242564e+00,
       1.54659634e-01, 3.39921176e-01, 1.01332716e+00, 1.76929030e+00,
       1.73769555e+00, 7.06025747e-02, 6.51607313e-02, 8.35950143e-02,
       1.64824370e+00, 2.07812335e-01, 1.81374850e+00, 1.17897780e+00,
       5.73182585e-02, 1.38206604e+00, 3.39011067e-01, 6.80663779e-02,
       3.69011988e-01, 1.19044204e-01, 1.64137901e+00, 1.77092449e+00,
       1.81282821e-01, 9.02739422e-02, 2.66684608e-01, 1.11272633e+00,
       3.86743153e-01, 1.49995373e-01, 5.79461566e-02, 1.45525997e-01,
       1.74814264e+00, 1.08419525e+00, 5.17432587e-01, 1.72284398e-01,
      

In [35]:
np.sqrt(np.sum(X_train.values**2,axis=1))*np.sqrt(np.sum(X_test.iloc[1].values**2))

array([  9.6420938 ,  36.62733783,  47.35188334,  41.88686505,
        49.30596779, 110.95893974,  89.42717118,  65.28198828,
        48.378738  ,  94.26827844,  90.89719782,  95.8468314 ,
        87.08750729, 127.18298834,  76.72704058,  51.18499311,
        67.53571473,  76.03357758, 125.55380588,  76.60377434,
        47.59953659,  83.05484247,  92.18805459, 127.12894979,
        92.51489901,  31.10288165,  45.21424737,  70.55305422,
       125.86057099,  90.65812297, 105.03457779, 107.35911287,
       122.37263709,  79.5388156 , 188.42145942,  43.85837745,
       104.93223973,  44.90105903,  38.04363904,  39.67240082,
        42.94733183, 115.10117599,  49.85544987,  32.03691786,
        48.81330192, 125.26200739,  78.68445948,  30.61429296,
        28.94125524,  92.50915495, 104.73726044,  53.80662494,
       202.25357225,   6.6632826 ,  45.30140697,  68.97725272,
        48.50770741,  67.98303837,  76.86633842,  84.57983963,
        79.97028698, 106.3607405 ,  36.02489381,  66.12

In [37]:
np.sqrt(np.sum(X_train.values**2,axis=1))

array([ 1.05624855,  4.01236217,  5.18718849,  4.58852001,  5.40124976,
       12.15505899,  9.79634938,  7.15135184,  5.29967586, 10.32667118,
        9.95738427, 10.49959464,  9.54004959, 13.93233144,  8.40510649,
        5.60708864,  7.39823757,  8.32914069, 13.75386174,  8.39160322,
        5.2143178 ,  9.09828908, 10.0987919 , 13.92641176, 10.13459625,
        3.40718253,  4.95301996,  7.7287737 , 13.7874665 ,  9.93119468,
       11.50607145, 11.76071394, 13.40537883,  8.71312395, 20.64073394,
        4.80449044, 11.49486077,  4.91871157,  4.16751167,  4.34593529,
        4.70468944, 12.60882257,  5.46144308,  3.50950205,  5.3472804 ,
       13.72189651,  8.61953303,  3.35365981,  3.17038596, 10.13396701,
       11.47350165,  5.89427676, 22.15598046,  0.72993301,  4.96256791,
        7.55615165,  5.31380388,  7.44723988,  8.42036595,  9.26534574,
        8.76038972, 11.65134668,  3.9463671 ,  7.24325102,  6.71051783,
        2.67421876,  8.14337233,  4.6954781 ,  9.31359143, 11.89

In [36]:
np.sqrt(np.sum(X_test.iloc[1].values**2))

9.128622071835377

In [ ]:
np.power((X_train.values - X_test.iloc[1].values),2)

array([[3.54477344e-01, 6.75884254e+01, 8.59750362e+00, 9.51932292e+00],
       [5.27033032e+00, 4.08308220e+01, 3.08704900e-02, 7.49390625e+00],
       [6.78316960e-03, 1.65836273e+01, 3.90387536e+01, 4.64665447e+00],
       ...,
       [4.56757002e+01, 1.22102500e+00, 1.08882841e+01, 4.04814400e+00],
       [1.01281790e+01, 3.02280040e+01, 1.08599907e+01, 2.26562704e+00],
       [9.48750883e+00, 2.38038612e+02, 2.12451030e+02, 3.82777486e+00]])

In [ ]:
np.sqrt(np.sum((X_train.values - X_test.iloc[1].values)**2,axis=1))

array([9.27683832e+00, 7.32297269e+00, 7.76375029e+00, 5.40954870e+00,
       1.09411989e+01, 4.87401304e+00, 1.83792177e+01, 4.31627010e+00,
       9.18456161e+00, 1.86572245e+01, 2.97545297e+00, 1.86806272e+01,
       5.33172475e+00, 2.20763354e+01, 6.41302058e+00, 5.01626770e+00,
       1.29580521e+01, 1.67778450e+01, 2.17415832e+01, 1.70542750e+01,
       1.14347015e+01, 1.75288962e+01, 1.86392823e+01, 2.21117046e+01,
       5.44321824e+00, 7.34029472e+00, 1.04436250e+01, 1.58624476e+01,
       2.14270749e+01, 3.66681287e+00, 4.39778641e+00, 4.98771298e+00,
       2.05351042e+01, 5.76462771e+00, 2.85661863e+01, 1.10505304e+01,
       4.19858929e+00, 1.19094838e+01, 7.09979195e+00, 5.31740596e+00,
       7.16012155e+00, 6.28617938e+00, 1.33083274e+01, 1.20434395e+01,
       5.65655116e+00, 6.61165339e+00, 6.49823361e+00, 1.00737703e+01,
       7.60830087e+00, 5.36307831e+00, 4.19960756e+00, 5.11092115e+00,
       2.96116236e+01, 9.21881644e+00, 8.01478981e+00, 5.12250643e+00,
      

In [ ]:
max_diffs = np.max(diffs, axis=1)

In [ ]:
len(max_diffs)

919

In [ ]:
max_values=[]
for i in range(X_train.shape[0]):
    max_value_i = max([s.iloc[i] for s in list_values])
    max_values.append(max_value_i)

In [ ]:
pd.Series(max_values, index=X_train.index)

1201     8.221218
1094     6.389900
224      6.248100
939      4.349600
274      8.049470
          ...    
1095     4.275100
1130    15.445100
1294     6.758380
860      5.498000
1126    15.428500
Length: 919, dtype: float64

In [ ]:
max_values

[8.221218,
 6.389900000000001,
 6.2481,
 4.349600000000001,
 8.049470000000001,
 4.16202,
 15.0022,
 3.4831,
 5.6905,
 15.4927,
 2.5708200000000003,
 14.6629,
 5.10582,
 16.817,
 3.9552799999999997,
 4.9559,
 10.2641,
 13.636500000000002,
 16.4797,
 14.7746,
 8.71784,
 14.636,
 15.0002,
 17.6592,
 5.26322,
 6.5596000000000005,
 7.910830000000001,
 13.6117,
 15.3002,
 3.2522200000000003,
 4.01322,
 4.64642,
 14.1156,
 5.07452,
 21.224600000000002,
 7.3603,
 3.7585200000000003,
 8.36607,
 4.6393,
 4.869,
 5.3118,
 5.716019999999999,
 10.8885,
 10.1043,
 4.2011,
 4.5748999999999995,
 4.11868,
 8.33089,
 6.5948,
 5.29942,
 3.73462,
 3.228618,
 21.218400000000003,
 8.233633000000001,
 5.6926000000000005,
 4.3455,
 5.055200000000001,
 4.0682,
 3.53868,
 3.5083200000000003,
 1.6241500000000002,
 3.63702,
 5.9388000000000005,
 2.81905,
 3.226048,
 7.95221,
 11.185199999999998,
 10.0505,
 1.43682,
 2.9431,
 3.54479,
 5.2373,
 20.9887,
 6.272,
 12.264600000000002,
 8.68267,
 20.680300000000003,


In [ ]:
X_train.loc[:,X_train.columns[1]]

1201   -0.033118
1094    1.798200
224     4.115800
939     3.838500
274     0.138630
          ...   
1095    3.913000
1130   -7.257000
1294    9.293100
860     2.690100
1126   -7.240400
Name: skewness, Length: 919, dtype: float64

In [ ]:
X_test[X_test.columns[1]]

430     6.34650
588     8.18810
296     7.05210
184    11.94590
244     9.38210
         ...   
141    -0.34765
705    -3.10390
654     2.90730
572    10.36710
139     9.22070
Name: skewness, Length: 453, dtype: float64